/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package i52salia.si.trabajofinal.aircontrol;

/**
 *
 * @author andres
 */
public final class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public HomePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backHomeButton = new javax.swing.JButton();
        backACButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        programMainPanel = new javax.swing.JPanel();
        devicesListMainPanel = new javax.swing.JPanel();
        scrollPanePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        programsList = new javax.swing.JPanel();
        devicesListButtonsPanel = new javax.swing.JPanel();
        addDeviceButton = new javax.swing.JButton();

        backHomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/si/trabajofinal/aircontrol/resources/images/back-icon.png"))); // NOI18N

        backACButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/si/trabajofinal/aircontrol/resources/images/back-icon.png"))); // NOI18N

        setLayout(new javax.swing.OverlayLayout(this));

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        programMainPanel.setEnabled(false);
        programMainPanel.setLayout(new javax.swing.BoxLayout(programMainPanel, javax.swing.BoxLayout.Y_AXIS));
        jPanel1.add(programMainPanel);

        devicesListMainPanel.setLayout(new java.awt.BorderLayout());

        scrollPanePanel.setLayout(new java.awt.GridLayout(1, 0));

        programsList.setLayout(new javax.swing.BoxLayout(programsList, javax.swing.BoxLayout.LINE_AXIS));
        scrollPane.setViewportView(programsList);

        scrollPanePanel.add(scrollPane);

        devicesListMainPanel.add(scrollPanePanel, java.awt.BorderLayout.CENTER);

        devicesListButtonsPanel.setLayout(new java.awt.GridBagLayout());

        addDeviceButton.setText("Add New Device");
        devicesListButtonsPanel.add(addDeviceButton, new java.awt.GridBagConstraints());

        devicesListMainPanel.add(devicesListButtonsPanel, java.awt.BorderLayout.SOUTH);

        jPanel1.add(devicesListMainPanel);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeviceButton;
    private javax.swing.JButton backACButton;
    private javax.swing.JButton backHomeButton;
    private javax.swing.JPanel devicesListButtonsPanel;
    private javax.swing.JPanel devicesListMainPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel programMainPanel;
    private javax.swing.JPanel programsList;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel scrollPanePanel;
    // End of variables declaration//GEN-END:variables
}
