package i52salia.si.trabajofinal.aircontrol;

public final class HomePanel extends javax.swing.JPanel {

    public HomePanel() {
        initComponents();
        customizeComponents();
    }
    
    public void customizeComponents() {
        deviceListMainPanel.setVisible(true);
        deviceSettingsMainPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deviceListMainPanel = new javax.swing.JPanel();
        deviceListScrollPane = new javax.swing.JScrollPane();
        deviceList = new javax.swing.JPanel();
        deviceListButtonsPanel = new javax.swing.JPanel();
        addDeviceButton = new javax.swing.JButton();
        deviceSettingsMainPanel = new javax.swing.JPanel();
        deviceSettingsScrollPane = new javax.swing.JScrollPane();
        deviceSettingsList = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deviceSettingsButtonsPanel = new javax.swing.JPanel();
        moreSettingsButton = new javax.swing.JButton();

        setLayout(new javax.swing.OverlayLayout(this));

        deviceListMainPanel.setLayout(new java.awt.BorderLayout());

        deviceListScrollPane.setBorder(null);

        deviceList.setLayout(new java.awt.GridLayout(0, 1));
        deviceListScrollPane.setViewportView(deviceList);

        deviceListMainPanel.add(deviceListScrollPane, java.awt.BorderLayout.CENTER);

        deviceListButtonsPanel.setLayout(new java.awt.GridBagLayout());

        addDeviceButton.setText("Add New Device");
        deviceListButtonsPanel.add(addDeviceButton, new java.awt.GridBagConstraints());

        deviceListMainPanel.add(deviceListButtonsPanel, java.awt.BorderLayout.SOUTH);

        add(deviceListMainPanel);

        deviceSettingsMainPanel.setEnabled(false);
        deviceSettingsMainPanel.setLayout(new java.awt.BorderLayout());

        deviceSettingsScrollPane.setBorder(null);

        deviceSettingsList.setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));

        jToggleButton1.setText("jToggleButton1");

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jToggleButton1)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        deviceSettingsList.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Temperature"));

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        deviceSettingsList.add(jPanel2);

        deviceSettingsScrollPane.setViewportView(deviceSettingsList);

        deviceSettingsMainPanel.add(deviceSettingsScrollPane, java.awt.BorderLayout.CENTER);

        deviceSettingsButtonsPanel.setLayout(new java.awt.GridBagLayout());

        moreSettingsButton.setText("More Settings");
        deviceSettingsButtonsPanel.add(moreSettingsButton, new java.awt.GridBagConstraints());

        deviceSettingsMainPanel.add(deviceSettingsButtonsPanel, java.awt.BorderLayout.SOUTH);

        add(deviceSettingsMainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeviceButton;
    public javax.swing.JPanel deviceList;
    private javax.swing.JPanel deviceListButtonsPanel;
    public javax.swing.JPanel deviceListMainPanel;
    private javax.swing.JScrollPane deviceListScrollPane;
    private javax.swing.JPanel deviceSettingsButtonsPanel;
    public javax.swing.JPanel deviceSettingsList;
    public javax.swing.JPanel deviceSettingsMainPanel;
    private javax.swing.JScrollPane deviceSettingsScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton moreSettingsButton;
    // End of variables declaration//GEN-END:variables
}
