package i52salia.aircontrol.panels;

/**
 * JPanel for the Programming tab.
 *
 * (Most of the code was automatically generated by NetBeans).
 *
 * @author Andrés Salinas Lima (i52salia@uco.es)
 */
public final class ProgrammingPanel extends javax.swing.JPanel {

    /**
     * Creates and initializes the JPanel.
     */
    public ProgrammingPanel() {
        initComponents();

        // Hide subpanels
        programListMainPanel.setVisible(true);
        programSettingsMainPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programListMainPanel = new javax.swing.JPanel();
        programListScrollPane = new javax.swing.JScrollPane();
        programListPanel = new javax.swing.JPanel();
        programListButtonsPanel = new javax.swing.JPanel();
        addProgramButton = new javax.swing.JButton();
        programSettingsMainPanel = new javax.swing.JPanel();
        programSettingsScrollPane = new javax.swing.JScrollPane();
        programSettingsListPanel = new javax.swing.JPanel();
        devicePanel = new javax.swing.JPanel();
        deviceLabel = new javax.swing.JLabel();
        StatusPanel = new javax.swing.JPanel();
        toggleButton = new i52salia.aircontrol.components.ToggleButton();
        daysOfWeekPanel = new javax.swing.JPanel();
        daysOfWeekSelector = new i52salia.aircontrol.components.DaysOfWeekSelector();
        timeFramePanel = new javax.swing.JPanel();
        timeFrameSelector = new i52salia.aircontrol.components.TimeFrameSelector();
        setPointTempPanel = new javax.swing.JPanel();
        setpointTemperatureSelector = new i52salia.aircontrol.components.SetpointTemperatureSelector();
        modePanel = new javax.swing.JPanel();
        modeSelector = new i52salia.aircontrol.components.ModeSelector();
        fanSpeedPanel = new javax.swing.JPanel();
        fanSpeedSelector = new i52salia.aircontrol.components.FanSpeedSelector();
        programSettingsButtonsPanel = new javax.swing.JPanel();
        programSettingsButtonsPanel2 = new javax.swing.JPanel();
        deletteButton = new javax.swing.JButton();
        programSettingsButtonsPanel3 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        invisibleSeparator = new javax.swing.JSeparator();
        saveButton = new javax.swing.JButton();

        setLayout(new javax.swing.OverlayLayout(this));

        programListMainPanel.setLayout(new java.awt.BorderLayout());

        programListScrollPane.setBorder(null);

        programListPanel.setLayout(new javax.swing.BoxLayout(programListPanel, javax.swing.BoxLayout.Y_AXIS));
        programListScrollPane.setViewportView(programListPanel);

        programListMainPanel.add(programListScrollPane, java.awt.BorderLayout.CENTER);

        programListButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        addProgramButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/save-program-icon.png"))); // NOI18N
        addProgramButton.setText("Add New Program");
        addProgramButton.setEnabled(false);
        programListButtonsPanel.add(addProgramButton);

        programListMainPanel.add(programListButtonsPanel, java.awt.BorderLayout.SOUTH);

        add(programListMainPanel);

        programSettingsMainPanel.setEnabled(false);
        programSettingsMainPanel.setLayout(new java.awt.BorderLayout());

        programSettingsScrollPane.setBorder(null);

        programSettingsListPanel.setLayout(new javax.swing.BoxLayout(programSettingsListPanel, javax.swing.BoxLayout.Y_AXIS));

        devicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Device"));
        devicePanel.setMaximumSize(new java.awt.Dimension(500, 100));

        deviceLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deviceLabel.setText("jLabel2");
        devicePanel.add(deviceLabel);

        programSettingsListPanel.add(devicePanel);

        StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));
        StatusPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        StatusPanel.add(toggleButton);

        programSettingsListPanel.add(StatusPanel);

        daysOfWeekPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Days of the Week"));
        daysOfWeekPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        daysOfWeekPanel.add(daysOfWeekSelector);

        programSettingsListPanel.add(daysOfWeekPanel);

        timeFramePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Frame"));
        timeFramePanel.setMaximumSize(new java.awt.Dimension(500, 100));
        timeFramePanel.add(timeFrameSelector);

        programSettingsListPanel.add(timeFramePanel);

        setPointTempPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Setpoint Temperature"));
        setPointTempPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        setPointTempPanel.add(setpointTemperatureSelector);

        programSettingsListPanel.add(setPointTempPanel);

        modePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mode"));
        modePanel.setMaximumSize(new java.awt.Dimension(500, 100));
        modePanel.add(modeSelector);

        programSettingsListPanel.add(modePanel);

        fanSpeedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Fan Speed"));
        fanSpeedPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        fanSpeedPanel.add(fanSpeedSelector);

        programSettingsListPanel.add(fanSpeedPanel);

        programSettingsScrollPane.setViewportView(programSettingsListPanel);

        programSettingsMainPanel.add(programSettingsScrollPane, java.awt.BorderLayout.CENTER);

        programSettingsButtonsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        programSettingsButtonsPanel.setLayout(new javax.swing.BoxLayout(programSettingsButtonsPanel, javax.swing.BoxLayout.Y_AXIS));

        deletteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/delete-program-icon.png"))); // NOI18N
        deletteButton.setText("Delete Program");
        deletteButton.setEnabled(false);
        deletteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        programSettingsButtonsPanel2.add(deletteButton);

        programSettingsButtonsPanel.add(programSettingsButtonsPanel2);

        programSettingsButtonsPanel3.setBorder(null);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/back-icon.png"))); // NOI18N
        cancelButton.setText("Cancel");
        programSettingsButtonsPanel3.add(cancelButton);

        invisibleSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        invisibleSeparator.setBorder(null);
        invisibleSeparator.setPreferredSize(new java.awt.Dimension(25, 0));
        programSettingsButtonsPanel3.add(invisibleSeparator);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/save-program-icon.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setEnabled(false);
        programSettingsButtonsPanel3.add(saveButton);

        programSettingsButtonsPanel.add(programSettingsButtonsPanel3);

        programSettingsMainPanel.add(programSettingsButtonsPanel, java.awt.BorderLayout.SOUTH);

        add(programSettingsMainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JButton addProgramButton;
    public javax.swing.JButton cancelButton;
    private javax.swing.JPanel daysOfWeekPanel;
    public i52salia.aircontrol.components.DaysOfWeekSelector daysOfWeekSelector;
    private javax.swing.JButton deletteButton;
    public javax.swing.JLabel deviceLabel;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JPanel fanSpeedPanel;
    public i52salia.aircontrol.components.FanSpeedSelector fanSpeedSelector;
    private javax.swing.JSeparator invisibleSeparator;
    private javax.swing.JPanel modePanel;
    public i52salia.aircontrol.components.ModeSelector modeSelector;
    private javax.swing.JPanel programListButtonsPanel;
    public javax.swing.JPanel programListMainPanel;
    public javax.swing.JPanel programListPanel;
    private javax.swing.JScrollPane programListScrollPane;
    private javax.swing.JPanel programSettingsButtonsPanel;
    private javax.swing.JPanel programSettingsButtonsPanel2;
    private javax.swing.JPanel programSettingsButtonsPanel3;
    public javax.swing.JPanel programSettingsListPanel;
    public javax.swing.JPanel programSettingsMainPanel;
    private javax.swing.JScrollPane programSettingsScrollPane;
    private javax.swing.JButton saveButton;
    private javax.swing.JPanel setPointTempPanel;
    public i52salia.aircontrol.components.SetpointTemperatureSelector setpointTemperatureSelector;
    private javax.swing.JPanel timeFramePanel;
    private i52salia.aircontrol.components.TimeFrameSelector timeFrameSelector;
    public i52salia.aircontrol.components.ToggleButton toggleButton;
    // End of variables declaration//GEN-END:variables
}
