package i52salia.aircontrol;

import i52salia.aircontrol.panels.SettingsPanel;
import i52salia.aircontrol.panels.HomePanel;
import i52salia.aircontrol.panels.ProgrammingPanel;
import java.awt.Dimension;

/**
 * The main View of the AirControl App.
 *
 * @author Andrés Salinas Lima (i52salia@uco.es)
 */
public final class View extends javax.swing.JFrame {

    /**
     * Initial dimensions for the AirControl App main window.
     */
    private final static Dimension INITIAL_SIZE = new Dimension(500, 700);

    private ProgrammingPanel programmingPanel;
    private HomePanel homePanel;
    private SettingsPanel settingsPanel;

    /**
     * Creates and initializes the JPanel.
     */
    public View() {
        initComponents();
        initSubcomponents();

        // Set initial dimensions
        this.setPreferredSize(INITIAL_SIZE);
        this.setSize(INITIAL_SIZE);
    }

    private void initSubcomponents() {
        programmingPanel = new ProgrammingPanel();
        programmingPanel.setVisible(false);
        mainPanel.add(programmingPanel);

        homePanel = new HomePanel();
        homePanel.setVisible(true);
        mainPanel.add(homePanel);

        settingsPanel = new SettingsPanel();
        settingsPanel.setVisible(false);
        mainPanel.add(settingsPanel);
    }

    /**
     * @return the programming tab panel
     */
    public ProgrammingPanel getProgrammingPanel() {
        return programmingPanel;
    }

    /**
     * @return the home tab panel
     */
    public HomePanel getHomePanel() {
        return homePanel;
    }

    /**
     * @return the settings tab panel
     */
    public SettingsPanel getSettingsPanel() {
        return settingsPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        tabBarPanel = new javax.swing.JPanel();
        programmingTab = new javax.swing.JPanel();
        programmingTabIcon = new javax.swing.JLabel();
        ProgrammingTabLabel = new javax.swing.JLabel();
        homeTab = new javax.swing.JPanel();
        homeTabIcon = new javax.swing.JLabel();
        homeTabLabel = new javax.swing.JLabel();
        settingsTab = new javax.swing.JPanel();
        settingsTabIcon = new javax.swing.JLabel();
        settingsTabLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AirControl");

        titlePanel.setBackground(new java.awt.Color(0, 195, 255));

        titleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleLabel.setText("titleLabel");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel)
        );

        getContentPane().add(titlePanel, java.awt.BorderLayout.NORTH);

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        mainPanel.setLayout(new javax.swing.OverlayLayout(mainPanel));
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        tabBarPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        tabBarPanel.setLayout(new java.awt.GridLayout(1, 3));

        programmingTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        programmingTab.setLayout(new java.awt.GridLayout(2, 1));

        programmingTabIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        programmingTabIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/programming-icon.png"))); // NOI18N
        programmingTabIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        programmingTab.add(programmingTabIcon);

        ProgrammingTabLabel.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        ProgrammingTabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i52salia/aircontrol/resources/languagebundles/Bundle"); // NOI18N
        ProgrammingTabLabel.setText(bundle.getString("View.tabs.Programming")); // NOI18N
        programmingTab.add(ProgrammingTabLabel);

        tabBarPanel.add(programmingTab);

        homeTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        homeTab.setMinimumSize(new java.awt.Dimension(0, 0));
        homeTab.setLayout(new java.awt.GridLayout(2, 1));

        homeTabIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTabIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/home-icon.png"))); // NOI18N
        homeTabIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        homeTab.add(homeTabIcon);

        homeTabLabel.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        homeTabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeTabLabel.setText(bundle.getString("View.tabs.Home")); // NOI18N
        homeTabLabel.setBorder(null);
        homeTab.add(homeTabLabel);

        tabBarPanel.add(homeTab);

        settingsTab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        settingsTab.setLayout(new java.awt.GridLayout(2, 1));

        settingsTabIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsTabIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/i52salia/aircontrol/resources/images/settings-icon.png"))); // NOI18N
        settingsTabIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));
        settingsTab.add(settingsTabIcon);

        settingsTabLabel.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        settingsTabLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsTabLabel.setText(bundle.getString("View.tabs.Settings")); // NOI18N
        settingsTabLabel.setBorder(null);
        settingsTab.add(settingsTabLabel);

        tabBarPanel.add(settingsTab);

        getContentPane().add(tabBarPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProgrammingTabLabel;
    public javax.swing.JPanel homeTab;
    private javax.swing.JLabel homeTabIcon;
    private javax.swing.JLabel homeTabLabel;
    private javax.swing.JPanel mainPanel;
    public javax.swing.JPanel programmingTab;
    private javax.swing.JLabel programmingTabIcon;
    public javax.swing.JPanel settingsTab;
    private javax.swing.JLabel settingsTabIcon;
    private javax.swing.JLabel settingsTabLabel;
    private javax.swing.JPanel tabBarPanel;
    public javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
