package i52salia.si.trabajofinal.aircontrol;

public final class ProgrammingPanel extends javax.swing.JPanel {

    public ProgrammingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        programsListMainPanel = new javax.swing.JPanel();
        scrollPanePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        programsList = new javax.swing.JPanel();
        programsListButtonsPanel = new javax.swing.JPanel();
        addProgramButton = new javax.swing.JButton();
        programMainPanel = new javax.swing.JPanel();

        setLayout(new javax.swing.OverlayLayout(this));

        programsListMainPanel.setLayout(new java.awt.BorderLayout());

        scrollPanePanel.setLayout(new java.awt.GridLayout());

        programsList.setLayout(new javax.swing.BoxLayout(programsList, javax.swing.BoxLayout.LINE_AXIS));
        scrollPane.setViewportView(programsList);

        scrollPanePanel.add(scrollPane);

        programsListMainPanel.add(scrollPanePanel, java.awt.BorderLayout.CENTER);

        programsListButtonsPanel.setLayout(new java.awt.GridBagLayout());

        addProgramButton.setText("Add New Program");
        programsListButtonsPanel.add(addProgramButton, new java.awt.GridBagConstraints());

        programsListMainPanel.add(programsListButtonsPanel, java.awt.BorderLayout.SOUTH);

        add(programsListMainPanel);

        programMainPanel.setEnabled(false);
        programMainPanel.setLayout(new javax.swing.BoxLayout(programMainPanel, javax.swing.BoxLayout.Y_AXIS));
        add(programMainPanel);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProgramButton;
    private javax.swing.JPanel programMainPanel;
    private javax.swing.JPanel programsList;
    private javax.swing.JPanel programsListButtonsPanel;
    private javax.swing.JPanel programsListMainPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel scrollPanePanel;
    // End of variables declaration//GEN-END:variables
}
