package i52salia.aircontrol.components;

import i52salia.aircontrol.utils.DaysOfWeekSelection;
import java.awt.event.ActionListener;

/**
 * Java Swing Component (JPanel) to select the days of the week of an AC
 * program.
 *
 * (Some of the code was automatically generated by NetBeans and should not be
 * modified to avoid conflicts with the IDE).
 *
 * @author Andrés Salinas Lima (i52salia@uco.es)
 */
public final class DaysOfWeekSelector extends javax.swing.JPanel {

    /**
     * Creates and initializes the JPanel.
     */
    public DaysOfWeekSelector() {
        initComponents();
    }

    /**
     * @return the selection represented by the current state of the buttons
     */
    public DaysOfWeekSelection getSelection() {
        return new DaysOfWeekSelection(
                monButton.isSelected(),
                tueButton.isSelected(),
                wedButton.isSelected(),
                thuButton.isSelected(),
                friButton.isSelected(),
                satButton.isSelected(),
                sunButton.isSelected());
    }

    /**
     * Sets the selection that will be represented by the buttons.
     *
     * @param daysOfWeekSelection
     */
    public void setSelection(DaysOfWeekSelection daysOfWeekSelection) {
        monButton.setSelected(daysOfWeekSelection.isOnMondays());
        tueButton.setSelected(daysOfWeekSelection.isOnTuesdays());
        wedButton.setSelected(daysOfWeekSelection.isOnWednesdays());
        thuButton.setSelected(daysOfWeekSelection.isOnThursdays());
        friButton.setSelected(daysOfWeekSelection.isOnFridays());
        satButton.setSelected(daysOfWeekSelection.isOnSaturdays());
        sunButton.setSelected(daysOfWeekSelection.isOnSundays());
    }

    /**
     * Allows to add an ActionListener to all the buttons.
     *
     * @param l
     */
    public void addActionListener(ActionListener l) {
        monButton.addActionListener(l);
        tueButton.addActionListener(l);
        wedButton.addActionListener(l);
        thuButton.addActionListener(l);
        friButton.addActionListener(l);
        satButton.addActionListener(l);
        sunButton.addActionListener(l);
    }

    /**
     * Allows to enable/disable all the buttons.
     *
     * @param b
     */
    @Override
    public void setEnabled(boolean b) {
        monButton.setEnabled(b);
        tueButton.setEnabled(b);
        wedButton.setEnabled(b);
        thuButton.setEnabled(b);
        friButton.setEnabled(b);
        satButton.setEnabled(b);
        sunButton.setEnabled(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        weekdaysPanel = new javax.swing.JPanel();
        monButton = new javax.swing.JToggleButton();
        tueButton = new javax.swing.JToggleButton();
        wedButton = new javax.swing.JToggleButton();
        thuButton = new javax.swing.JToggleButton();
        friButton = new javax.swing.JToggleButton();
        weekendPanel = new javax.swing.JPanel();
        satButton = new javax.swing.JToggleButton();
        sunButton = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        weekdaysPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 2));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i52salia/aircontrol/resources/languagebundles/Bundle"); // NOI18N
        monButton.setText(bundle.getString("DaysOfWeekSelection.Mon")); // NOI18N
        weekdaysPanel.add(monButton);

        tueButton.setText(bundle.getString("DaysOfWeekSelection.Tue")); // NOI18N
        weekdaysPanel.add(tueButton);

        wedButton.setText(bundle.getString("DaysOfWeekSelection.Wed")); // NOI18N
        weekdaysPanel.add(wedButton);

        thuButton.setText(bundle.getString("DaysOfWeekSelection.Thu")); // NOI18N
        weekdaysPanel.add(thuButton);

        friButton.setText(bundle.getString("DaysOfWeekSelection.Fri")); // NOI18N
        weekdaysPanel.add(friButton);

        add(weekdaysPanel, java.awt.BorderLayout.NORTH);

        weekendPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 2));

        satButton.setText(bundle.getString("DaysOfWeekSelection.Sat")); // NOI18N
        weekendPanel.add(satButton);

        sunButton.setText(bundle.getString("DaysOfWeekSelection.Sun")); // NOI18N
        weekendPanel.add(sunButton);

        add(weekendPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton friButton;
    private javax.swing.JToggleButton monButton;
    private javax.swing.JToggleButton satButton;
    private javax.swing.JToggleButton sunButton;
    private javax.swing.JToggleButton thuButton;
    private javax.swing.JToggleButton tueButton;
    private javax.swing.JToggleButton wedButton;
    private javax.swing.JPanel weekdaysPanel;
    private javax.swing.JPanel weekendPanel;
    // End of variables declaration//GEN-END:variables
}
