package i52salia.aircontrol.components;

import i52salia.aircontrol.utils.ACProgram;
import i52salia.aircontrol.utils.Temperature;
import i52salia.aircontrol.utils.Time;

/**
 * Java Swing Component (JPanel) used to show the AC program settings.
 *
 * (Much of the code was automatically generated by NetBeans).
 *
 * @author Andrés Salinas Lima (i52salia@uco.es)
 */
public class ProgramSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates and initializes the JPanel.
     */
    public ProgramSettingsPanel() {
        initComponents();
    }

    /**
     * @param tempUnit the temperature unit to be used by the setpoint
     * temperature selector
     */
    public void setTemperatureUnit(Temperature.TempUnit tempUnit) {
        setpointTemperatureSelector.setTemperatureUnit(tempUnit);
    }

    /**
     * @param timeFormat the time format to be used by the time frame selector
     */
    public void setTimeFormat(Time.TimeFormat timeFormat) {
        timeFrameSelector.setTimeFormat(timeFormat);
    }

    /**
     * @return a program with the selected settings
     */
    public ACProgram getSelectedProgram() {
        ACProgram program = new ACProgram();

        program.setEnabled(toggleButton.isToggledOn());
        program.setDaysOfWeekSelection(daysOfWeekSelector.getSelection());
        program.setTimeFrame(timeFrameSelector.getSelectedTimeFrame());
        program.setSetpointTemp(setpointTemperatureSelector.getSelectedTemperature());
        program.setMode(modeSelector.getSelectedMode());
        program.setFanSpeed(fanSpeedSelector.getSelectedFanSpeed());

        return program;
    }

    /**
     * @param program the program whose settings will be preselected in the
     * selectors
     */
    public void setSelectedProgram(ACProgram program) {
        toggleButton.setToggledOn(program.isEnabled());
        daysOfWeekSelector.setSelection(program.getDaysOfWeekSelection());
        timeFrameSelector.setSelectedTimeFrame(program.getTimeFrame());
        setpointTemperatureSelector.setSelectedTemperature(program.getSetpointTemp());
        modeSelector.setSelectedMode(program.getMode());
        fanSpeedSelector.setSelectedFanSpeed(program.getFanSpeed());
    }
    
    public void setSelectedDeviceName(String name) {
        deviceLabel.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        devicePanel = new javax.swing.JPanel();
        deviceLabel = new javax.swing.JLabel();
        StatusPanel = new javax.swing.JPanel();
        toggleButton = new i52salia.aircontrol.components.ToggleButton();
        daysOfWeekPanel = new javax.swing.JPanel();
        daysOfWeekSelector = new i52salia.aircontrol.components.DaysOfWeekSelector();
        timeFramePanel = new javax.swing.JPanel();
        timeFrameSelector = new i52salia.aircontrol.components.TimeFrameSelector();
        setPointTempPanel = new javax.swing.JPanel();
        setpointTemperatureSelector = new i52salia.aircontrol.components.SetpointTemperatureSelector();
        modePanel = new javax.swing.JPanel();
        modeSelector = new i52salia.aircontrol.components.ModeSelector();
        fanSpeedPanel = new javax.swing.JPanel();
        fanSpeedSelector = new i52salia.aircontrol.components.FanSpeedSelector();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("i52salia/aircontrol/resources/languagebundles/Bundle"); // NOI18N
        devicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ACProgram.Device"))); // NOI18N
        devicePanel.setMaximumSize(new java.awt.Dimension(500, 100));

        deviceLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        deviceLabel.setText("jLabel2");
        devicePanel.add(deviceLabel);

        add(devicePanel);

        StatusPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ACProgram.Status"))); // NOI18N
        StatusPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        StatusPanel.add(toggleButton);

        add(StatusPanel);

        daysOfWeekPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ACProgram.DaysWeek"))); // NOI18N
        daysOfWeekPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        daysOfWeekPanel.add(daysOfWeekSelector);

        add(daysOfWeekPanel);

        timeFramePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ACProgram.TimeFrame"))); // NOI18N
        timeFramePanel.setMaximumSize(new java.awt.Dimension(500, 100));
        timeFramePanel.add(timeFrameSelector);

        add(timeFramePanel);

        setPointTempPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AirConditioner.SetTemp"))); // NOI18N
        setPointTempPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        setPointTempPanel.add(setpointTemperatureSelector);

        add(setPointTempPanel);

        modePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AirConditioner.Mode"))); // NOI18N
        modePanel.setMaximumSize(new java.awt.Dimension(500, 100));
        modePanel.add(modeSelector);

        add(modePanel);

        fanSpeedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("AirConditioner.FanSpeed"))); // NOI18N
        fanSpeedPanel.setMaximumSize(new java.awt.Dimension(500, 100));
        fanSpeedPanel.add(fanSpeedSelector);

        add(fanSpeedPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JPanel daysOfWeekPanel;
    public i52salia.aircontrol.components.DaysOfWeekSelector daysOfWeekSelector;
    public javax.swing.JLabel deviceLabel;
    private javax.swing.JPanel devicePanel;
    private javax.swing.JPanel fanSpeedPanel;
    public i52salia.aircontrol.components.FanSpeedSelector fanSpeedSelector;
    private javax.swing.JPanel modePanel;
    public i52salia.aircontrol.components.ModeSelector modeSelector;
    private javax.swing.JPanel setPointTempPanel;
    public i52salia.aircontrol.components.SetpointTemperatureSelector setpointTemperatureSelector;
    private javax.swing.JPanel timeFramePanel;
    public i52salia.aircontrol.components.TimeFrameSelector timeFrameSelector;
    public i52salia.aircontrol.components.ToggleButton toggleButton;
    // End of variables declaration//GEN-END:variables
}
